<!DOCTYPE html>
<html>
<head>
    <title>Invoice</title>
</head>
<body>
    <p>
        This Report,<br>
        Generated By,<br>
        i-Delivery System
    </p>
    <p>
        ________________________________________________________________________________________
    </p>
    <table style="width:100%">
        <tr>
            <th>
                To<br>
                {{$myInvoice->menu->getOwner->name}}
            </th>
            <th style="background-color: #d9d9d9; font-size:20px; font-weight: bolder;"> </th>
            <th>INVOICE</th>
          </tr>
          <tr>
            <td>     </td>
            <td>
                INVOICE DATE<br>
                ________________<br>
                {{-- {{$myInvoice->created_at}} --}}
                <b><?php echo date('d M Y', strtotime($myInvoice->created_at))?></b>
            </td>
            <td>
                INVOICE NO<br>
                ________________<br>
                {{$myInvoice->id}}
            </td>
          </tr>
          <tr>
            <td>     </td>
            <td>     </td>
            <td>   
                TOTAL<br>
                ________________<br>
                <b>RM{{number_format($grandTotal,2)}}</b>
            </td>
          </tr>
    </table>
    <div class="row" style="background-color: #d9d9d9; font-size:20px; font-weight: bolder;">
        Summary of Payments
    </div>
    <table id="adminMembers"  class="table table-striped projects"data-page-length="25" max-width =  "10px" style="width:100%">
        <thead>
          <tr>
            <th>  </th>
            <th>Menu</th>
            <th>Restaurant</th>
            <th>PRICE</th>
            <th>QUANTITY</th>
            <th>TOTAL</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($myOrderHistory as $key => $menu)
            <tr style="width: 100%; text-align: center;">
                <td>{{$key+1}}</td>
                <td>{{$menu->menu->name}}</td>
                <td>{{$menu->menu->getOwner->name}}</td>
                <td>{{number_format($menu->price,2)}}</td>
                <td>{{$menu->quantity}}</td>
                <td>
                    {{number_format($menu->price,2)}}
                </td>
              </tr> 
            @endforeach
        </tbody>
        <tfoot>
            <tr style="width: 100%;">
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
                <td style="text-align: right;"><b>Grand Total RM</b></td>
                <td style="text-align: center;"><b>{{number_format($grandTotal,2)}}</b></td>
            </tr>
        </tfoot>
      </table>
</body>
</html>